apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base

namespace: kuberstrike
resources:
  - ns.yaml
  - pv.yaml
  - ss.yaml

# configMapGenerator:
#   - name: kuberstrike
#     files:
#       - server.cfg

# patchesStrategicMerge:
#   - patch.yaml
