apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-csgo-awes-one
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: kuberstrike
    name: kuberstrike
  mountOptions:
    - hard
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: pv-csgo-awes-one
    volumeAttributes:
      server: 192.168.1.51
      share: /var/nfs/k8s/csgo.awes.one