apiVersion: v1
kind: Service
metadata:
  name: kuberstrike
spec:
  selector:
    app: kuberstrike
  type: NodePort
  ports:
    - name: csgo-udp
      port: 27015
      targetPort: 27015
      protocol: UDP